#!/usr/bin/env bash
#The file /etc/passwd has already been covered in a previous project and you should be familiar with it. Today we will make up a story based on it
while IFS=: read -r username password userid groupid useridinfo homedir shell
do
echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < /etc/passwd
