#!/usr/bin/env bash
#Escriba un script de Bash que muestre Best School 10 veces, pero para la novena iteración, muestre Best School y luego Hola en una nueva línea
i=1; while ((i<11));do echo "Best School";if ((i==9));then echo "Hi";fi; ((i++)); done

