#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes
Hour=0;while((hour<=12));do echo "Hour: ${Hour}";minutes=1;while((minutes<=59));do echo "${minutes}";((++minutes));done;((++Hour));done
