#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:display hours from 0 to 12
hours=0; while ((hours<=12)); do echo "hours: ${hours}"; minutes=1; while ((minutes<=59)); do echo "${minutes}"; ((++minutes));done; ((++hours));done
