#!/usr/bin/env bash
#Write a Bash script that displaysThe content of the current directoryIn a list formatWhere only the part of the name after the first dash is displayed (refer to the example)
file=$(ls); for f in $file; do echo "$f" | cut -d "-" -f2; done
