#!/usr/bin/env bash
#Write a Bash script that:Creates the file /var/run/myscript.pid containing its PIDDisplays To infinity and beyond indefinitelyDisplays I hate the kill command when receiving a SIGTERM signalDisplays Y U no love me?! when receiving a SIGINT signalDeletes the file /var/run/myscript.pid and terminates itself when receiving a SiGQUIT or SIGTERM signal
no_file()
{
rm -rf "/var/run/myscript.pid" ;
}
k_process()
{
pkill -9 -f "10-process_and_pid_file" ;
}
echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command' ; no_file ; k_process " SIGTERM
trap "no_file ; k_process" SIGQUIT
trap "echo 'Y U no love me?!'" SIGNIT

while (true)
do
	echo "To infinity and beyond"
	sleep 2
done
