#!/usr/bin/env bash
#Write a Bash script that:Creates the file /var/run/myscript.pid containing its PIDDisplays To infinity and beyond indefinitelyDisplays I hate the kill command when receiving a SIGTERM signalDisplays Y U no love me?! when receiving a SIGINT signalDeletes the file /var/run/myscript.pid and terminates itself when receiving a SiGQUIT or SIGTERM signal
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; deleteandkill' SIGTERM
trap 'deleteandkill' SIGQUIT
deleteandkill(){
sudo rm /var/run/myscript.pid; exit;}


echo $$ >> /var/run/myscript.pid
while (true)
do 
	echo "To infinity and beyond"
	sleep 2
done
