#!/usr/bin/env bash
#Write a Bash script thatCreates the file /var/run/myscript.pid containing its PIDDisplays To infinity and beyond indefinitelyDisplays I hate the kill command when receiving a SIGTERM signalDisplays Y U no love me?! when receiving a SIGINT signalDeletes the file /var/run/myscript.pid and terminates itself when receiving a S GQUIT or SIGTERM signal
deletefileandexit(){
rm -f /var/run/myscript.pid;
exit
}

trap "echo 'Y U no love me?!' deletefileandexit" SIGNIT
trap "echo 'I hate the kill command'; deletefileandexit" SIGTERM
trap "echo 'I hate the kill command'; deletefileandexit" SIGQUIT

echo $$ >> /var/run/myscript.pid
while : ; do
	echo "To infinity and beyond"
	sleep 2
done
